spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fx_db
    username: demo_user
    password: change_me
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Server port (optional)
server:
  port: 8080
